# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# SEE README.debusine.md BEFORE CHANGING THIS FILE

name: Debusine Release

on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: Packaging branch to build and optionally release
        type: string
        required: true
        default: qcom/debian/trixie
      release:
        description: Run release step
        type: boolean
        required: true
        default: false

jobs:
  debusine:
    name: Debusine
    uses: qualcomm-linux/debusine-action/.github/workflows/debusine.yml@dev/sbeaudoi
    with:
      target_branch: ${{ inputs.target-branch }}
      source_ref: refs/heads/${{ inputs.target-branch }}
      release: ${{ inputs.release }}
      debusine-parent-workspace: ${{ vars.DEBUSINE_PARENT_WORKSPACE || 'ci' }}
    permissions:
      contents: write
      deployments: write
      id-token: write
      packages: read
    secrets:
      DEBUSINE_USER: ${{ secrets.DEBUSINE_USER }}
      DEBUSINE_TOKEN: ${{ secrets.DEBUSINE_TOKEN }}
      DEBUSINE_RELEASE_TOKEN: ${{ secrets.DEBUSINE_RELEASE_TOKEN }}
