name: Release Version
description: |
  Release a new package version.
  This workflow is manually triggered via workflow_dispatch.

on:
  workflow_dispatch:
    inputs:

      suite:
        description: The distribution codename or Debian suite to release for. Ex noble, questing, resolute, trixie, bookworm, sid, unstable
        type: choice
        default: noble
        options:
          - noble
          - questing
          - resolute
          - unstable
          - forky
          - trixie
          - bookworm
          - sid

      debian-branch:
        description: The debian branch to use to execute the release from. For example branch "debian/qcom-next"
        type: string
        required: false
        default: debian/qcom-next

      test-run:
        description: |
          If true, the built packages will be uploaded to the 'test' folder in S3.
          If false, the built packages will be uploaded to the 'proposed' folder in S3
        type: boolean
        default: true

permissions:
  contents: write
  packages: read
  id-token: write

jobs:
  release:

    uses: qualcomm-linux/qcom-build-utils/.github/workflows/qcom-release-reusable-workflow.yml@development
    with:
      suite: ${{ github.event.inputs.suite }}
      debian-branch: ${{ github.event.inputs.debian-branch }}
      debusine-parent-workspace: ${{ vars.DEBUSINE_PARENT_WORKSPACE || 'ci' }}
    secrets:
      PAT: ${{ secrets.DEB_PKG_BOT_CI_TOKEN }}
      DEBUSINE_USER: ${{ secrets.DEBUSINE_USER }}
      DEBUSINE_TOKEN: ${{ secrets.DEBUSINE_TOKEN }}
      DEBUSINE_RELEASE_TOKEN: ${{ secrets.DEBUSINE_RELEASE_TOKEN }}